// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlGenerated

type Query struct {
}

type Torrents struct {
	Client     string  `json:"Client"`
	Name       string  `json:"Name"`
	Category   string  `json:"Category"`
	Ratio      float64 `json:"Ratio"`
	InfoHashV1 string  `json:"InfoHashV1"`
	Comment    string  `json:"Comment"`
	RootPath   string  `json:"RootPath"`
	SavePath   string  `json:"SavePath"`
	SizeBytes  int64   `json:"SizeBytes"`
	Tracker    string  `json:"Tracker"`
}
