// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlGenerated

type Category struct {
	Name    string   `json:"Name"`
	Path    string   `json:"Path"`
	Servers []string `json:"Servers"`
}

type CreateCategoryArgs struct {
	Name string `json:"Name"`
	Path string `json:"Path"`
}

type CreateCategoryResult struct {
	Success bool `json:"Success"`
}

type DeleteTorrentInfo struct {
	Server string `json:"Server"`
	Hash   string `json:"Hash"`
}

type DeleteTorrentsArgs struct {
	Torrents []*DeleteTorrentInfo `json:"Torrents"`
}

type DeleteTorrentsResults struct {
	Success bool `json:"Success"`
}

type File struct {
	Availability float64 `json:"Availability"`
	Index        int     `json:"Index"`
	IsSeed       bool    `json:"IsSeed"`
	Name         string  `json:"Name"`
	PieceRange   []int   `json:"PieceRange"`
	Priority     int     `json:"Priority"`
	Progress     float64 `json:"Progress"`
	SizeBytes    int64   `json:"SizeBytes"`
}

type Mutation struct {
}

type PauseTorrentInfo struct {
	Server string `json:"Server"`
	Hash   string `json:"Hash"`
}

type PauseTorrentsArgs struct {
	Torrents []*PauseTorrentInfo `json:"Torrents"`
}

type PauseTorrentsResults struct {
	Success bool `json:"Success"`
}

type Query struct {
}

type ResumeTorrentInfo struct {
	Server string `json:"Server"`
	Hash   string `json:"Hash"`
}

type ResumeTorrentsArgs struct {
	Torrents []*ResumeTorrentInfo `json:"Torrents"`
}

type ResumeTorrentsResults struct {
	Success bool `json:"Success"`
}

type Torrent struct {
	Server     string    `json:"Server"`
	Name       string    `json:"Name"`
	Category   string    `json:"Category"`
	Ratio      float64   `json:"Ratio"`
	InfoHashV1 string    `json:"InfoHashV1"`
	Comment    string    `json:"Comment"`
	RootPath   string    `json:"RootPath"`
	SavePath   string    `json:"SavePath"`
	SizeBytes  int64     `json:"SizeBytes"`
	Trackers   []Tracker `json:"Trackers"`
	TrackerURL string    `json:"TrackerUrl"`
	Files      []File    `json:"Files"`
	AddedOn    int64     `json:"AddedOn"`
	State      string    `json:"State"`
}

type Tracker struct {
	Tier            int    `json:"Tier"`
	URL             string `json:"Url"`
	Status          string `json:"Status"`
	Peers           int    `json:"Peers"`
	Seeds           int    `json:"Seeds"`
	Leeches         int    `json:"Leeches"`
	TimesDownloaded int    `json:"TimesDownloaded"`
	Message         string `json:"Message"`
}
