// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlGenerated

import (
	"github.com/99designs/gqlgen/graphql"
)

type Category struct {
	Name    string   `json:"Name"`
	Path    string   `json:"Path"`
	Servers []string `json:"Servers"`
}

type CreateCategoryArgs struct {
	Name string `json:"Name"`
	Path string `json:"Path"`
}

type CreateCategoryResult struct {
	Success bool `json:"Success"`
}

type File struct {
	Availability float64 `json:"Availability"`
	Index        int     `json:"Index"`
	IsSeed       bool    `json:"IsSeed"`
	Name         string  `json:"Name"`
	PieceRange   []int   `json:"PieceRange"`
	Priority     int     `json:"Priority"`
	Progress     float64 `json:"Progress"`
	SizeBytes    int64   `json:"SizeBytes"`
}

type Mutation struct {
}

type Query struct {
}

type Torrent struct {
	Server     string  `json:"Server"`
	Name       string  `json:"Name"`
	Category   string  `json:"Category"`
	Ratio      float64 `json:"Ratio"`
	InfoHashV1 string  `json:"InfoHashV1"`
	Comment    string  `json:"Comment"`
	RootPath   string  `json:"RootPath"`
	SavePath   string  `json:"SavePath"`
	SizeBytes  int64   `json:"SizeBytes"`
	Tracker    string  `json:"Tracker"`
	Files      []File  `json:"Files"`
}

type UploadTorrentArgs struct {
	File     []*graphql.Upload `json:"File"`
	Category *string           `json:"Category,omitempty"`
}

type UploadTorrentResult struct {
	Success bool `json:"Success"`
}
