### POST try login
POST https://{{hostname}}/api/v2/auth/login
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://{{hostname}}

username={{username}}&password={{password}}

### Get categories
GET https://{{hostname}}/api/v2/torrents/categories

### Get torrents
GET https://{{hostname}}/api/v2/torrents/info?sort=added_on

### Get torrent contents
GET https://{{hostname}}/api/v2/torrents/files?hash={{hash}}

### Get torrent properties
GET https://{{hostname}}/api/v2/torrents/properties?hash={{hash}}

### Get torrent info
GET https://{{hostname}}/api/v2/torrents/info?hashes={{hash}}

### Get torrent trackers
GET https://{{hostname}}/api/v2/torrents/trackers?hash={{hash}}

### Get torrent pieces hash
GET https://{{hostname}}/api/v2/torrents/pieceHashes?hash={{hash}}

### Get incemental data
GET https://{{hostname}}/api/v2/sync/maindata?rid=3

### Pause Torrents
POST https://{{hostname}}/api/v2/torrents/stop
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://{{hostname}}

hashes =