// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Torrent struct {
	InfoHashV1  string
	ServerUrl   string
	Name        string
	LastUpdated int64
	Path        string
}
