// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createTorrent = `-- name: CreateTorrent :exec
INSERT INTO torrents (info_hash_v1,
                      server_url,
                      name,
                      last_updated,
                      path)
VALUES (?, ?, ?, ?, ?)
on conflict (info_hash_v1,server_url) do update
    set name         = excluded.name,
        last_updated = excluded.last_updated,
        path         = excluded.path
`

type CreateTorrentParams struct {
	InfoHashV1  string
	ServerUrl   string
	Name        string
	LastUpdated int64
	Path        string
}

func (q *Queries) CreateTorrent(ctx context.Context, arg CreateTorrentParams) error {
	_, err := q.db.ExecContext(ctx, createTorrent,
		arg.InfoHashV1,
		arg.ServerUrl,
		arg.Name,
		arg.LastUpdated,
		arg.Path,
	)
	return err
}

const getTorrents = `-- name: GetTorrents :many
SELECT info_hash_v1, server_url, name, last_updated, path
FROM torrents
`

func (q *Queries) GetTorrents(ctx context.Context) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, getTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHashV1,
			&i.ServerUrl,
			&i.Name,
			&i.LastUpdated,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTorrentsByInfoHash = `-- name: GetTorrentsByInfoHash :many
SELECT info_hash_v1, server_url, name, last_updated, path
FROM torrents
WHERE info_hash_v1 = ?
`

func (q *Queries) GetTorrentsByInfoHash(ctx context.Context, infoHashV1 string) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, getTorrentsByInfoHash, infoHashV1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHashV1,
			&i.ServerUrl,
			&i.Name,
			&i.LastUpdated,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
