// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :exec
insert into categories (name, save_path, server_url)
values (?, ?, ?)
on conflict do update
    SET save_path = excluded.save_path
`

type CreateCategoryParams struct {
	Name      string
	SavePath  string
	ServerUrl string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory, arg.Name, arg.SavePath, arg.ServerUrl)
	return err
}

const createServer = `-- name: CreateServer :exec
insert into qb_servers (url, last_seen)
values (?, ?)
on conflict do nothing
`

type CreateServerParams struct {
	Url      string
	LastSeen int64
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.ExecContext(ctx, createServer, arg.Url, arg.LastSeen)
	return err
}

const createTorrent = `-- name: CreateTorrent :exec
INSERT INTO torrents (info_hash_v1,
                      server_url,
                      name,
                      last_updated,
                      path,
                      category,
                      ratio,
                      comment,
                      rootPath,
                      savePath,
                      sizeBytes,
                      addedOn,
                      state)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict (info_hash_v1, server_url) do update
    set name         = excluded.name,
        last_updated = excluded.last_updated,
        path         = excluded.path,
        category     = excluded.category,
        ratio        = excluded.ratio,
        comment      = excluded.comment,
        rootPath     = excluded.rootPath,
        savePath     = excluded.savePath,
        sizeBytes    = excluded.sizeBytes,
        addedOn      = excluded.addedOn,
        state        = excluded.state
`

type CreateTorrentParams struct {
	InfoHashV1  string
	ServerUrl   string
	Name        string
	LastUpdated int64
	Path        string
	Category    sql.NullString
	Ratio       float64
	Comment     string
	Rootpath    string
	Savepath    string
	Sizebytes   int64
	Addedon     int64
	State       string
}

func (q *Queries) CreateTorrent(ctx context.Context, arg CreateTorrentParams) error {
	_, err := q.db.ExecContext(ctx, createTorrent,
		arg.InfoHashV1,
		arg.ServerUrl,
		arg.Name,
		arg.LastUpdated,
		arg.Path,
		arg.Category,
		arg.Ratio,
		arg.Comment,
		arg.Rootpath,
		arg.Savepath,
		arg.Sizebytes,
		arg.Addedon,
		arg.State,
	)
	return err
}

const createTorrentFile = `-- name: CreateTorrentFile :exec
INSERT INTO torrent_files (info_hash_v1,
                            server_url,
                            availability,
                            name,
                            file_index,
                            piece_range_start,
                            piece_range_end,
                            priority,
                            progress,
                            size,
                            is_seed)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (info_hash_v1, server_url, name) DO UPDATE
    SET availability      = excluded.availability,
        file_index        = excluded.file_index,
        piece_range_start = excluded.piece_range_start,
        piece_range_end   = excluded.piece_range_end,
        priority          = excluded.priority,
        progress          = excluded.progress,
        size              = excluded.size,
        is_seed           = excluded.is_seed
`

type CreateTorrentFileParams struct {
	InfoHashV1      string
	ServerUrl       string
	Availability    float64
	Name            string
	FileIndex       int64
	PieceRangeStart int64
	PieceRangeEnd   int64
	Priority        int64
	Progress        float64
	Size            int64
	IsSeed          int64
}

func (q *Queries) CreateTorrentFile(ctx context.Context, arg CreateTorrentFileParams) error {
	_, err := q.db.ExecContext(ctx, createTorrentFile,
		arg.InfoHashV1,
		arg.ServerUrl,
		arg.Availability,
		arg.Name,
		arg.FileIndex,
		arg.PieceRangeStart,
		arg.PieceRangeEnd,
		arg.Priority,
		arg.Progress,
		arg.Size,
		arg.IsSeed,
	)
	return err
}

const createTrackerTorrent = `-- name: CreateTrackerTorrent :exec
INSERT INTO trackers_torrents (info_hash_v1,
                               server_url,
                               url,
                               tier,
                               status,
                               num_peers,
                               num_seeds,
                               num_leeches,
                               num_downloaded,
                               msg)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (url, info_hash_v1, server_url) DO UPDATE
    SET tier           = excluded.tier,
        status         = excluded.status,
        num_peers      = excluded.num_peers,
        num_seeds      = excluded.num_seeds,
        num_leeches    = excluded.num_leeches,
        num_downloaded = excluded.num_downloaded,
        msg            = excluded.msg
`

type CreateTrackerTorrentParams struct {
	InfoHashV1    string
	ServerUrl     string
	Url           string
	Tier          int64
	Status        int64
	NumPeers      int64
	NumSeeds      int64
	NumLeeches    int64
	NumDownloaded int64
	Msg           string
}

func (q *Queries) CreateTrackerTorrent(ctx context.Context, arg CreateTrackerTorrentParams) error {
	_, err := q.db.ExecContext(ctx, createTrackerTorrent,
		arg.InfoHashV1,
		arg.ServerUrl,
		arg.Url,
		arg.Tier,
		arg.Status,
		arg.NumPeers,
		arg.NumSeeds,
		arg.NumLeeches,
		arg.NumDownloaded,
		arg.Msg,
	)
	return err
}

const getTorrents = `-- name: GetTorrents :many
SELECT info_hash_v1, server_url, name, last_updated, path, category, ratio, comment, rootpath, savepath, sizebytes, addedon, state
FROM torrents
order by server_url
`

func (q *Queries) GetTorrents(ctx context.Context) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, getTorrents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHashV1,
			&i.ServerUrl,
			&i.Name,
			&i.LastUpdated,
			&i.Path,
			&i.Category,
			&i.Ratio,
			&i.Comment,
			&i.Rootpath,
			&i.Savepath,
			&i.Sizebytes,
			&i.Addedon,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTorrentsByInfoHash = `-- name: GetTorrentsByInfoHash :many
SELECT info_hash_v1, server_url, name, last_updated, path, category, ratio, comment, rootpath, savepath, sizebytes, addedon, state
FROM torrents
WHERE info_hash_v1 = ?
`

func (q *Queries) GetTorrentsByInfoHash(ctx context.Context, infoHashV1 string) ([]Torrent, error) {
	rows, err := q.db.QueryContext(ctx, getTorrentsByInfoHash, infoHashV1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Torrent
	for rows.Next() {
		var i Torrent
		if err := rows.Scan(
			&i.InfoHashV1,
			&i.ServerUrl,
			&i.Name,
			&i.LastUpdated,
			&i.Path,
			&i.Category,
			&i.Ratio,
			&i.Comment,
			&i.Rootpath,
			&i.Savepath,
			&i.Sizebytes,
			&i.Addedon,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
