package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/database"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/helpers"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/qbClient"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/sqlc"
)

// Torrents is the resolver for the Torrents field.
func (r *queryResolver) Torrents(ctx context.Context, categories []string, servers []string) ([]gqlGenerated.Torrent, error) {
	db := database.MustGet()
	queries := sqlc.New(db)

	torrents, err := queries.GetTorrents(ctx)
	if err != nil {
		return nil, err
	}

	rtnMe := make([]gqlGenerated.Torrent, len(torrents))

	for i, t := range torrents {
		rtnMe[i] = gqlGenerated.Torrent{
			Server:     t.ServerUrl,
			Name:       t.Name,
			Category:   t.Category.String,
			Ratio:      t.Ratio,
			InfoHashV1: t.InfoHashV1,
			Comment:    t.Comment,
			RootPath:   t.Rootpath,
			SavePath:   t.Savepath,
			SizeBytes:  t.Sizebytes,
			AddedOn:    t.Addedon,
			State:      t.State,
		}
	}

	return rtnMe, nil
}

// Categories is the resolver for the Categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]gqlGenerated.Category, error) {
	categories, err := helpers.GetAllCategories(ctx)
	if err != nil {
		return nil, err
	}

	rtnMe := make([]gqlGenerated.Category, 0)

	for _, category := range categories {
		rtnMe = append(rtnMe, gqlGenerated.Category{
			Name:    category.Name,
			Path:    category.SavePath,
			Servers: category.Servers,
		})
	}

	slices.SortFunc(rtnMe, func(a, b gqlGenerated.Category) int {
		return strings.Compare(a.Name, b.Name)
	})

	return rtnMe, nil
}

// Torrent is the resolver for the Torrent field.
func (r *queryResolver) Torrent(ctx context.Context, infoHashV1 string) ([]*gqlGenerated.Torrent, error) {
	clients := qbClient.Registry().All()

	rtnMe := make([]*gqlGenerated.Torrent, 0)

	for _, client := range clients {
		torrent, errL := client.GetTorrent(ctx, infoHashV1)
		if errL != nil {
			if errors.Is(errL, qbClient.TorrentNotFoundError) {
				continue
			} else {
				return nil, errL
			}
		}

		rtnMe = append(rtnMe, &gqlGenerated.Torrent{
			Server:     client.BasePath.String(),
			Name:       torrent.Name,
			Category:   torrent.Category,
			Ratio:      torrent.Ratio,
			InfoHashV1: torrent.InfohashV1,
			Comment:    torrent.Comment,
			RootPath:   torrent.RootPath,
			SavePath:   torrent.SavePath,
			SizeBytes:  torrent.Size,
			TrackerURL: torrent.Tracker,
		})
	}

	if len(rtnMe) == 0 {
		return nil, errors.New("torrent not found")
	}
	return rtnMe, nil
}

// Trackers is the resolver for the Trackers field.
func (r *torrentResolver) Trackers(ctx context.Context, obj *gqlGenerated.Torrent) ([]gqlGenerated.Tracker, error) {
	client, exist := qbClient.Registry().Get(obj.Server)

	if !exist {
		return nil, fmt.Errorf("client not found")
	}

	trackers, err := client.GetTracker(ctx, obj.InfoHashV1)
	if err != nil {
		return nil, err
	}

	rtnMe := make([]gqlGenerated.Tracker, len(trackers))

	for i, tracker := range trackers {
		currGqlTracker := gqlGenerated.Tracker{
			Tier:            tracker.Tier,
			URL:             tracker.Url,
			Status:          tracker.StatusString(),
			Peers:           tracker.NumPeers,
			Seeds:           tracker.NumSeeds,
			Leeches:         tracker.NumLeeches,
			TimesDownloaded: tracker.NumDownloaded,
			Message:         tracker.Msg,
		}
		rtnMe[i] = currGqlTracker
	}
	return rtnMe, nil
}

// Files is the resolver for the Files field.
func (r *torrentResolver) Files(ctx context.Context, obj *gqlGenerated.Torrent) ([]gqlGenerated.File, error) {
	client, exist := qbClient.Registry().Get(obj.Server)

	if !exist {
		return nil, fmt.Errorf("client not found")
	}

	files, err := client.GetFilesInTorrent(ctx, obj.InfoHashV1)
	if err != nil {
		return nil, err
	}

	rtnMe := make([]gqlGenerated.File, 0)

	for _, file := range files {
		curr := gqlGenerated.File{
			Availability: file.Availability,
			Index:        file.Index,
			IsSeed:       file.IsSeed,
			Name:         file.Name,
			PieceRange:   file.PieceRange,
			Priority:     file.Priority,
			Progress:     file.Progress,
			SizeBytes:    file.Size,
		}
		rtnMe = append(rtnMe, curr)
	}
	if len(rtnMe) == 0 {
		return nil, errors.New("no files found")
	}

	return rtnMe, nil
}

// Query returns gqlGenerated.QueryResolver implementation.
func (r *Resolver) Query() gqlGenerated.QueryResolver { return &queryResolver{r} }

// Torrent returns gqlGenerated.TorrentResolver implementation.
func (r *Resolver) Torrent() gqlGenerated.TorrentResolver { return &torrentResolver{r} }

type queryResolver struct{ *Resolver }
type torrentResolver struct{ *Resolver }
