package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/qbClient"
)

// Torrents is the resolver for the Torrents field.
func (r *queryResolver) Torrents(ctx context.Context) ([]*gqlGenerated.Torrents, error) {
	clients, err := qbClient.GetClients(ctx)
	if err != nil {
		return nil, err
	}
	rtnMe := make([]*gqlGenerated.Torrents, 0)

	for _, client := range clients {
		torrents, errL := client.GetTorrents(ctx)
		if errL != nil {
			return nil, err
		}

		for _, torrent := range torrents {
			curr := &gqlGenerated.Torrents{
				Client:     torrent.Client.BasePath.String(),
				Name:       torrent.Name,
				Category:   torrent.Category,
				Ratio:      torrent.Ratio,
				InfoHashV1: torrent.InfohashV1,
				Comment:    torrent.Comment,
				RootPath:   torrent.RootPath,
				SavePath:   torrent.SavePath,
				SizeBytes:  torrent.Size,
				Tracker:    torrent.Tracker,
			}
			rtnMe = append(rtnMe, curr)
		}
	}

	return rtnMe, nil
}

// Query returns gqlGenerated.QueryResolver implementation.
func (r *Resolver) Query() gqlGenerated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
