package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/qbClient"
)

// Torrents is the resolver for the Torrents field.
func (r *queryResolver) Torrents(ctx context.Context) ([]*gqlGenerated.Torrent, error) {
	clients, err := qbClient.GetClients(ctx)
	if err != nil {
		return nil, err
	}
	rtnMe := make([]*gqlGenerated.Torrent, 0)

	for _, client := range clients {
		torrents, errL := client.GetTorrents(ctx)
		if errL != nil {
			return nil, err
		}

		for _, torrent := range torrents {
			curr := &gqlGenerated.Torrent{
				Client:     torrent.Client.BasePath.String(),
				Name:       torrent.Name,
				Category:   torrent.Category,
				Ratio:      torrent.Ratio,
				InfoHashV1: torrent.InfohashV1,
				Comment:    torrent.Comment,
				RootPath:   torrent.RootPath,
				SavePath:   torrent.SavePath,
				SizeBytes:  torrent.Size,
				Tracker:    torrent.Tracker,
			}
			rtnMe = append(rtnMe, curr)
		}
	}

	return rtnMe, nil
}

// Files is the resolver for the Files field.
func (r *torrentResolver) Files(ctx context.Context, obj *gqlGenerated.Torrent) ([]*gqlGenerated.File, error) {
	clients, err := qbClient.GetClients(ctx)
	if err != nil {
		return nil, err
	}

	var client *qbClient.Client
	for _, clientL := range clients {
		if clientL.BasePath.String() != obj.Client {
			continue
		}
		client = clientL
	}
	if client == nil {
		return nil, fmt.Errorf("client not found")
	}

	files, err := client.GetFilesInTorrent(ctx, obj.InfoHashV1)
	if err != nil {
		return nil, err
	}

	rtnMe := make([]*gqlGenerated.File, 0)

	for _, file := range files {
		curr := &gqlGenerated.File{
			Availability: file.Availability,
			Index:        file.Index,
			IsSeed:       file.IsSeed,
			Name:         file.Name,
			PieceRange:   file.PieceRange,
			Priority:     file.Priority,
			Progress:     file.Progress,
			SizeBytes:    file.Size,
		}
		rtnMe = append(rtnMe, curr)
	}

	return rtnMe, nil
}

// Query returns gqlGenerated.QueryResolver implementation.
func (r *Resolver) Query() gqlGenerated.QueryResolver { return &queryResolver{r} }

// Torrent returns gqlGenerated.TorrentResolver implementation.
func (r *Resolver) Torrent() gqlGenerated.TorrentResolver { return &torrentResolver{r} }

type queryResolver struct{ *Resolver }
type torrentResolver struct{ *Resolver }
