package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
)

// TorrentsSyncAPI is the resolver for the TorrentsSyncApi field.
func (r *queryResolver) TorrentsSyncAPI(ctx context.Context, args gqlGenerated.TorrentSyncAPIArgs) (*gqlGenerated.SyncAPIResults, error) {
	panic(fmt.Errorf("not implemented: TorrentsSyncAPI - TorrentsSyncApi"))
}
