package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/qbClient"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, args gqlGenerated.CreateCategoryArgs) (*gqlGenerated.CreateCategoryResult, error) {
	clients := qbClient.Registry().All()

	currCategory := &qbClient.Category{
		Name:     args.Name,
		SavePath: args.Path,
	}

	for _, client := range clients {
		err := client.CreateCategoryIfNotExist(ctx, currCategory)
		if err != nil {
			return nil, err
		}
	}
	return &gqlGenerated.CreateCategoryResult{Success: true}, nil
}

// PauseTorrents is the resolver for the pauseTorrents field.
func (r *mutationResolver) PauseTorrents(ctx context.Context, args gqlGenerated.PauseTorrentsArgs) (*gqlGenerated.PauseTorrentsResults, error) {
	torrentsToPause := make(map[string][]string)

	for _, currTorrent := range args.Torrents {
		torrentsToPause[currTorrent.Server] = append(torrentsToPause[currTorrent.Server], currTorrent.Hash)
	}

	for server, hashes := range torrentsToPause {
		client, exist := qbClient.Registry().Get(server)
		if !exist {
			return nil, errors.New("server not found in registry")
		}

		errL := client.PauseTorrents(ctx, hashes)
		if errL != nil {
			return nil, errL
		}
	}

	return &gqlGenerated.PauseTorrentsResults{Success: true}, nil
}

// ResumeTorrents is the resolver for the resumeTorrents field.
func (r *mutationResolver) ResumeTorrents(ctx context.Context, args gqlGenerated.ResumeTorrentsArgs) (*gqlGenerated.ResumeTorrentsResults, error) {
	torrentsToResume := make(map[string][]string)

	for _, currTorrent := range args.Torrents {
		torrentsToResume[currTorrent.Server] = append(torrentsToResume[currTorrent.Server], currTorrent.Hash)
	}

	for server, hashes := range torrentsToResume {
		client, exist := qbClient.Registry().Get(server)
		if !exist {
			return nil, errors.New("server not found in registry")
		}

		errL := client.ResumeTorrents(ctx, hashes)
		if errL != nil {
			return nil, errL
		}
	}

	return &gqlGenerated.ResumeTorrentsResults{Success: true}, nil
}

// Mutation returns gqlGenerated.MutationResolver implementation.
func (r *Resolver) Mutation() gqlGenerated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
