package gqlResolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"

	"github.com/kingsukhoi/qbitorrent-panel/pkg/gqlGenerated"
	"github.com/kingsukhoi/qbitorrent-panel/pkg/qbClient"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, args gqlGenerated.CreateCategoryArgs) (*gqlGenerated.CreateCategoryResult, error) {
	clients := qbClient.Registry().All()

	currCategory := &qbClient.Category{
		Name:     args.Name,
		SavePath: args.Path,
	}

	for _, client := range clients {
		err := client.CreateCategoryIfNotExist(ctx, currCategory)
		if err != nil {
			return nil, err
		}
	}
	return &gqlGenerated.CreateCategoryResult{Success: true}, nil
}

// UploadTorrent is the resolver for the uploadTorrent field.
func (r *mutationResolver) UploadTorrent(ctx context.Context, args gqlGenerated.UploadTorrentArgs) (*gqlGenerated.UploadTorrentResult, error) {
	return nil, errors.New("fuck off")
}

// Mutation returns gqlGenerated.MutationResolver implementation.
func (r *Resolver) Mutation() gqlGenerated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
